name = "FisherWright"
uuid = "a555c6d9-8fd4-4ecd-87f6-904b8d8d9cbe"
authors = ["Xijiang Yu <xijiang@users.noreply.github.com>"]
version = "0.1.1"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
DataFrames = "1.8.0"
Distributions = "0.25.120"
Random = "1.11.0"
Statistics = "1.11.1"
